### PR TITLE
Initial package setup

### PR DESCRIPTION
**Pull request by rth**
Mostly boilerplate code to set up the package adapted from pytest-pyodide, matplotlib-pyodide etc.

### CODE REVIEW

**Comment by rth** [comment]
It does look like we have some misconfiguration for pre-commit, because it does find things to fix in code I copy-paster from the Pyodide repo. Where pre-commit should have been running on them.

**Comment by hoodmane** [comment]
I think @henryiii specifically excluded the externals directory based on the idea that we didn't want to change code copied out of other projects.

**Comment by rth** [comment]
Yeah but for instance, in https://github.com/pyodide/micropip/pull/1/commits/851b14b7a73f9e0a814a10c8c72b9b795518498d triggered by pre-comit there is a linter change in `micropip/_micropip.py` and in `tests/test_micropip.py`. So it's not just externals. With a monorepo it's  hard to make sure that path regexes are correct everywhere, because there are so many things...

**Comment by hoodmane** [comment]
Probably would be good to revert the changes to the externals directory.

**Comment by rth** [comment]
I did in earlier commits..

**Comment by hoodmane** [comment]
> I did in earlier commits..

Sorry!

Recently I have also been getting the following error:
```
/home/hood/.cache/pre-commit/repow1xom7p_/py_env-3.10/lib/python3.10/site-packages/numpy/__init__.pyi:636: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
```

**Pull request merged**
